image: node:18-bullseye-slim

stages:
  - lint
  - tsc
  - checks

before_script:
  - npm install

lint:
  stage: lint
  only:
    - master
    - merge_requests
  script:
    - npm run lint

tsc:
  stage: tsc
  only:
    - master
    - merge_requests
  script:
    - npm run tsc

tests:
  stage: checks
  only:
    - master
    - merge_requests
  script:
    - SERVER_LOG=$(mktemp)
    - npm run start >& $SERVER_LOG &
    - timeout 10s grep -q "⚡️ Server started on port" <(tail -f $SERVER_LOG) || (cat $SERVER_LOG && exit 1)
    - timeout -s SIGINT 180s npm run test || (cat $SERVER_LOG && exit 1)
    - kill -SIGINT %1
    - sleep 2
    - cat $SERVER_LOG
